apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica-set1
spec:
  replicas: 3
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - rsexample1
  template:
    metadata:
      labels:
        app: rsexample1
    spec:
      containers:
      - name: rscontainer
        image: aamirpinger/helloworld:latest
        ports:
        - containerPort: 80